### PR TITLE
migrate to tweaker

### PR DESCRIPTION
**Pull request by Wyvest**

### CODE REVIEW

**Review by pauliesnug — APPROVED** [review]
3 things: 
1. i told you we needed to use tweaker
2. lgtm
3. you already migrated oneconfig so we kind of have to migrate wrapper

**Comment by pauliesnug** [comment]
i would merge this but someone removed my write access >:d

**Review by nextdayy — APPROVED** [review]
lgtm

**Comment by Shiggy-dev** [comment]
looks good me to

**Pull request merged**
